package org.appfuse.webapp.taglib;

import junit.framework.TestCase;
// JUnitDoclet end import

/**
* Generated by JUnitDoclet, a tool provided by
* ObjectFab GmbH under LGPL.
* Please see www.junitdoclet.org, www.gnu.org
* and www.objectfab.de for informations about
* the tool, the licence and the authors.
*/


public class SecureTest
// JUnitDoclet begin extends_implements
extends TestCase
// JUnitDoclet end extends_implements
{
  // JUnitDoclet begin class
  org.appfuse.webapp.taglib.Secure secure = null;
  // JUnitDoclet end class
  
  public SecureTest(String name) {
    // JUnitDoclet begin method SecureTest
    super(name);
    // JUnitDoclet end method SecureTest
  }
  
  public org.appfuse.webapp.taglib.Secure createInstance() throws Exception {
    // JUnitDoclet begin method testcase.createInstance
    return new org.appfuse.webapp.taglib.Secure();
    // JUnitDoclet end method testcase.createInstance
  }
  
  protected void setUp() throws Exception {
    // JUnitDoclet begin method testcase.setUp
    super.setUp();
    secure = createInstance();
    // JUnitDoclet end method testcase.setUp
  }
  
  protected void tearDown() throws Exception {
    // JUnitDoclet begin method testcase.tearDown
    secure = null;
    super.tearDown();
    // JUnitDoclet end method testcase.tearDown
  }
  
  public void testSetMode() throws Exception {
    // JUnitDoclet begin method setMode
    // JUnitDoclet end method setMode
  }
  
  public void testDoStartTag() throws Exception {
    // JUnitDoclet begin method doStartTag
    // JUnitDoclet end method doStartTag
  }
  
  public void testDoAfterBody() throws Exception {
    // JUnitDoclet begin method doAfterBody
    // JUnitDoclet end method doAfterBody
  }
  
  public void testDoEndTag() throws Exception {
    // JUnitDoclet begin method doEndTag
    // JUnitDoclet end method doEndTag
  }
  
  
  
  /**
  * JUnitDoclet moves marker to this method, if there is not match
  * for them in the regenerated code and if the marker is not empty.
  * This way, no test gets lost when regenerating after renaming.
  * Method testVault is supposed to be empty.
  */
  public void testVault() throws Exception {
    // JUnitDoclet begin method testcase.testVault
    // JUnitDoclet end method testcase.testVault
  }
  
  public static void main(String[] args) {
    // JUnitDoclet begin method testcase.main
    junit.textui.TestRunner.run(SecureTest.class);
    // JUnitDoclet end method testcase.main
  }
}
