package org.appfuse.webapp.util;

import junit.framework.TestCase;
// JUnitDoclet end import

/**
* Generated by JUnitDoclet, a tool provided by
* ObjectFab GmbH under LGPL.
* Please see www.junitdoclet.org, www.gnu.org
* and www.objectfab.de for informations about
* the tool, the licence and the authors.
*/


public class RequestUtilTest
// JUnitDoclet begin extends_implements
extends TestCase
// JUnitDoclet end extends_implements
{
  // JUnitDoclet begin class
  org.appfuse.webapp.util.RequestUtil requestutil = null;
  // JUnitDoclet end class
  
  public RequestUtilTest(String name) {
    // JUnitDoclet begin method RequestUtilTest
    super(name);
    // JUnitDoclet end method RequestUtilTest
  }
  
  public org.appfuse.webapp.util.RequestUtil createInstance() throws Exception {
    // JUnitDoclet begin method testcase.createInstance
    return new org.appfuse.webapp.util.RequestUtil();
    // JUnitDoclet end method testcase.createInstance
  }
  
  protected void setUp() throws Exception {
    // JUnitDoclet begin method testcase.setUp
    super.setUp();
    requestutil = createInstance();
    // JUnitDoclet end method testcase.setUp
  }
  
  protected void tearDown() throws Exception {
    // JUnitDoclet begin method testcase.tearDown
    requestutil = null;
    super.tearDown();
    // JUnitDoclet end method testcase.tearDown
  }
  
  public void testGetRequestParameters() throws Exception {
    // JUnitDoclet begin method getRequestParameters
    // JUnitDoclet end method getRequestParameters
  }
  
  public void testCreateQueryStringFromMap() throws Exception {
    // JUnitDoclet begin method createQueryStringFromMap
    // JUnitDoclet end method createQueryStringFromMap
  }
  
  public void testStowRequestAttributes() throws Exception {
    // JUnitDoclet begin method stowRequestAttributes
    // JUnitDoclet end method stowRequestAttributes
  }
  
  public void testReclaimRequestAttributes() throws Exception {
    // JUnitDoclet begin method reclaimRequestAttributes
    // JUnitDoclet end method reclaimRequestAttributes
  }
  
  public void testGetCookie() throws Exception {
    // JUnitDoclet begin method getCookie
    // JUnitDoclet end method getCookie
  }
  
  public void testDeleteCookie() throws Exception {
    // JUnitDoclet begin method deleteCookie
    // JUnitDoclet end method deleteCookie
  }
  
  
  
  /**
  * JUnitDoclet moves marker to this method, if there is not match
  * for them in the regenerated code and if the marker is not empty.
  * This way, no test gets lost when regenerating after renaming.
  * Method testVault is supposed to be empty.
  */
  public void testVault() throws Exception {
    // JUnitDoclet begin method testcase.testVault
    // JUnitDoclet end method testcase.testVault
  }
  
  public static void main(String[] args) {
    // JUnitDoclet begin method testcase.main
    junit.textui.TestRunner.run(RequestUtilTest.class);
    // JUnitDoclet end method testcase.main
  }
}
