package org.appfuse.webapp.util;

import junit.framework.TestCase;
// JUnitDoclet end import

/**
* Generated by JUnitDoclet, a tool provided by
* ObjectFab GmbH under LGPL.
* Please see www.junitdoclet.org, www.gnu.org
* and www.objectfab.de for informations about
* the tool, the licence and the authors.
*/


public class SslUtilTest
// JUnitDoclet begin extends_implements
extends TestCase
// JUnitDoclet end extends_implements
{
  // JUnitDoclet begin class
  org.appfuse.webapp.util.SslUtil sslutil = null;
  // JUnitDoclet end class
  
  public SslUtilTest(String name) {
    // JUnitDoclet begin method SslUtilTest
    super(name);
    // JUnitDoclet end method SslUtilTest
  }
  
  public org.appfuse.webapp.util.SslUtil createInstance() throws Exception {
    // JUnitDoclet begin method testcase.createInstance
    return new org.appfuse.webapp.util.SslUtil();
    // JUnitDoclet end method testcase.createInstance
  }
  
  protected void setUp() throws Exception {
    // JUnitDoclet begin method testcase.setUp
    super.setUp();
    sslutil = createInstance();
    // JUnitDoclet end method testcase.setUp
  }
  
  protected void tearDown() throws Exception {
    // JUnitDoclet begin method testcase.tearDown
    sslutil = null;
    super.tearDown();
    // JUnitDoclet end method testcase.tearDown
  }
  
  public void testGetRedirectString() throws Exception {
    // JUnitDoclet begin method getRedirectString
    // JUnitDoclet end method getRedirectString
  }
  
  
  
  /**
  * JUnitDoclet moves marker to this method, if there is not match
  * for them in the regenerated code and if the marker is not empty.
  * This way, no test gets lost when regenerating after renaming.
  * Method testVault is supposed to be empty.
  */
  public void testVault() throws Exception {
    // JUnitDoclet begin method testcase.testVault
    // JUnitDoclet end method testcase.testVault
  }
  
  public static void main(String[] args) {
    // JUnitDoclet begin method testcase.main
    junit.textui.TestRunner.run(SslUtilTest.class);
    // JUnitDoclet end method testcase.main
  }
}
