package org.appfuse.webapp.action;

import junit.framework.TestCase;
// JUnitDoclet end import

/**
* Generated by JUnitDoclet, a tool provided by
* ObjectFab GmbH under LGPL.
* Please see www.junitdoclet.org, www.gnu.org
* and www.objectfab.de for informations about
* the tool, the licence and the authors.
*/


public class BaseActionTest
// JUnitDoclet begin extends_implements
extends TestCase
// JUnitDoclet end extends_implements
{
  // JUnitDoclet begin class
  BaseAction baseaction = null;
  // JUnitDoclet end class
  
  public BaseActionTest(String name) {
    // JUnitDoclet begin method BaseActionTest
    super(name);
    // JUnitDoclet end method BaseActionTest
  }
  
  public org.appfuse.webapp.action.BaseAction createInstance() throws Exception {
    // JUnitDoclet begin method testcase.createInstance
    return new BaseAction();
    // JUnitDoclet end method testcase.createInstance
  }
  
  protected void setUp() throws Exception {
    // JUnitDoclet begin method testcase.setUp
    super.setUp();
    baseaction = createInstance();
    // JUnitDoclet end method testcase.setUp
  }
  
  protected void tearDown() throws Exception {
    // JUnitDoclet begin method testcase.tearDown
    baseaction = null;
    super.tearDown();
    // JUnitDoclet end method testcase.tearDown
  }
  
  public void testGetKeyMethodMap() throws Exception {
    // JUnitDoclet begin method getKeyMethodMap
    // JUnitDoclet end method getKeyMethodMap
  }
  
  
  
  /**
  * JUnitDoclet moves marker to this method, if there is not match
  * for them in the regenerated code and if the marker is not empty.
  * This way, no test gets lost when regenerating after renaming.
  * Method testVault is supposed to be empty.
  */
  public void testVault() throws Exception {
    // JUnitDoclet begin method testcase.testVault
    // JUnitDoclet end method testcase.testVault
  }
  
  public static void main(String[] args) {
    // JUnitDoclet begin method testcase.main
    junit.textui.TestRunner.run(BaseActionTest.class);
    // JUnitDoclet end method testcase.main
  }
}
