package org.appfuse.webapp.action;

import org.apache.cactus.ServletTestCase;
import org.apache.cactus.WebRequest;
import org.apache.commons.logging.Log;
import org.apache.commons.logging.LogFactory;
import org.apache.struts.Globals;
import org.appfuse.Constants;


/**
 * Generated by JUnitDoclet, a tool provided by ObjectFab GmbH under LGPL.
 * Please see www.junitdoclet.org, www.gnu.org and www.objectfab.de for
 * informations about the tool, the licence and the authors.
 */
public class RegistrationServletTest extends ServletTestCase
// JUnitDoclet end extends_implements
 {
    //~ Instance fields ========================================================

    private Log log = LogFactory.getLog(RegistrationServletTest.class);

    // JUnitDoclet begin class
    RegistrationServlet servlet = null;

    //~ Constructors ===========================================================

    // JUnitDoclet end class
    public RegistrationServletTest(String name) {
        // JUnitDoclet begin method RegistrationServletTest
        super(name);

        // JUnitDoclet end method RegistrationServletTest
    }

    //~ Methods ================================================================

    public RegistrationServlet createInstance() throws Exception {
        // JUnitDoclet begin method testcase.createInstance
        return new RegistrationServlet();

        // JUnitDoclet end method testcase.createInstance
    }

    protected void setUp() throws Exception {
        // JUnitDoclet begin method testcase.setUp
        super.setUp();
        servlet = new RegistrationServlet();
        servlet.init(config);

        // JUnitDoclet end method testcase.setUp
    }

    protected void tearDown() throws Exception {
        // JUnitDoclet begin method testcase.tearDown
        servlet = null;
        super.tearDown();

        // JUnitDoclet end method testcase.tearDown
    }

    public void beginAddUser(WebRequest wRequest) {
        wRequest.addParameter("username", "self-registered");
        wRequest.addParameter("password", "Password1");
        wRequest.addParameter("confirmPassword", "Password1");
        wRequest.addParameter("firstName", "First");
        wRequest.addParameter("lastName", "Last");
        wRequest.addParameter("city", "Denver");
        wRequest.addParameter("province", "Colorado");
        wRequest.addParameter("country", "USA");
        wRequest.addParameter("postalCode", "80210");
        wRequest.addParameter("email", "self-registered@nospam.org");
        wRequest.addParameter("website", "http://raibledesigns.com");
        wRequest.addParameter("passwordHint", "Password is one with you.");
    }

    /**
     * This method tests adding a new user
     * @throws Exception
     */
    public void testAddUser() throws Exception {
        servlet.execute(request, response);

        // no errors
        assertTrue(request.getAttribute(Globals.ERROR_KEY) == null);

        // verify that success messages are in the request
        assertTrue(request.getSession().getAttribute(Constants.REGISTERED) != null);
    }

    /**
     * JUnitDoclet moves marker to this method, if there is not match for them
     * in the regenerated code and if the marker is not empty. This way, no
     * test gets lost when regenerating after renaming. Method testVault is
     * supposed to be empty.
     *
     * @throws Exception DOCUMENT ME!
     */
    public void testVault() throws Exception {
        // JUnitDoclet begin method testcase.testVault
        // JUnitDoclet end method testcase.testVault
    }

    public static void main(String[] args) {
        // JUnitDoclet begin method testcase.main
        junit.textui.TestRunner.run(RegistrationServletTest.class);

        // JUnitDoclet end method testcase.main
    }
}
