package org.appfuse.webapp.action;

import junit.framework.TestCase;


// JUnitDoclet end import

/**
 * Generated by JUnitDoclet, a tool provided by
 * ObjectFab GmbH under LGPL.
 * Please see www.junitdoclet.org, www.gnu.org
 * and www.objectfab.de for informations about
 * the tool, the licence and the authors.
 */
public class UploadActionTest extends TestCase
// JUnitDoclet end extends_implements
 {
    //~ Instance fields ========================================================

    // JUnitDoclet begin class
    UploadAction uploadaction = null;

    //~ Constructors ===========================================================

    // JUnitDoclet end class
    public UploadActionTest(String name) {
        // JUnitDoclet begin method UploadActionTest
        super(name);

        // JUnitDoclet end method UploadActionTest
    }

    //~ Methods ================================================================

    public org.appfuse.webapp.action.UploadAction createInstance()
      throws Exception {
        // JUnitDoclet begin method testcase.createInstance
        return new org.appfuse.webapp.action.UploadAction();

        // JUnitDoclet end method testcase.createInstance
    }

    protected void setUp() throws Exception {
        // JUnitDoclet begin method testcase.setUp
        super.setUp();
        uploadaction = createInstance();

        // JUnitDoclet end method testcase.setUp
    }

    protected void tearDown() throws Exception {
        // JUnitDoclet begin method testcase.tearDown
        uploadaction = null;
        super.tearDown();

        // JUnitDoclet end method testcase.tearDown
    }

    public void testExecute() throws Exception {
        // JUnitDoclet begin method execute
        // JUnitDoclet end method execute
    }

    /**
     * JUnitDoclet moves marker to this method, if there is not match
     * for them in the regenerated code and if the marker is not empty.
     * This way, no test gets lost when regenerating after renaming.
     * Method testVault is supposed to be empty.
     */
    public void testVault() throws Exception {
        // JUnitDoclet begin method testcase.testVault
        // JUnitDoclet end method testcase.testVault
    }

    public static void main(String[] args) {
        // JUnitDoclet begin method testcase.main
        junit.textui.TestRunner.run(UploadActionTest.class);

        // JUnitDoclet end method testcase.main
    }
}
