/**
${pojo.getClassJavaDoc(pojo.getDeclarationName() + " generated by AMP and Hibernate Tools ${version} on ${date}", 0)}
 */
<#include "Ejb3TypeDeclaration.ftl"/>
${pojo.getClassModifiers()} ${pojo.getDeclarationType()} ${pojo.getDeclarationName()} ${pojo.getExtendsDeclaration()} ${pojo.getImplementsDeclaration()}