    <managed-bean>
        <managed-bean-name>${pojo.shortName.toLowerCase()}List</managed-bean-name>
        <managed-bean-class>${basepackage}.webapp.action.${pojo.shortName}List</managed-bean-class>
        <managed-bean-scope>request</managed-bean-scope>
        <managed-property>
            <property-name>${pojo.shortName.toLowerCase()}Manager</property-name>
            <value>${'#'}{${pojo.shortName.toLowerCase()}Manager}</value>
        </managed-property>
    </managed-bean>

    <managed-bean>
        <managed-bean-name>${pojo.shortName.toLowerCase()}Form</managed-bean-name>
        <managed-bean-class>${basepackage}.webapp.action.${pojo.shortName}Form</managed-bean-class>
        <managed-bean-scope>request</managed-bean-scope>
        <managed-property>
            <property-name>id</property-name>
            <value>${'#'}{param.id}</value>
        </managed-property>
        <managed-property>
            <property-name>${pojo.shortName.toLowerCase()}Manager</property-name>
            <value>${'#'}{${pojo.shortName.toLowerCase()}Manager}</value>
        </managed-property>
    </managed-bean>