    <navigation-rule>
        <from-view-id>/${pojo.shortName.toLowerCase()}s.xhtml</from-view-id>
        <navigation-case>
            <from-outcome>add</from-outcome>
            <to-view-id>/${pojo.shortName.toLowerCase()}Form.xhtml</to-view-id>
        </navigation-case>
        <navigation-case>
            <from-outcome>edit</from-outcome>
            <to-view-id>/${pojo.shortName.toLowerCase()}Form.xhtml</to-view-id>
        </navigation-case>
    </navigation-rule>
    <navigation-rule>
        <from-view-id>/${pojo.shortName.toLowerCase()}Form.xhtml</from-view-id>
        <navigation-case>
            <from-outcome>cancel</from-outcome>
            <to-view-id>/${pojo.shortName.toLowerCase()}s.xhtml</to-view-id>
            <redirect/>
        </navigation-case>
        <navigation-case>
            <from-outcome>list</from-outcome>
            <to-view-id>/${pojo.shortName.toLowerCase()}s.xhtml</to-view-id>
            <redirect/>
        </navigation-case>
    </navigation-rule>